'use client'

import { useEffect, useState } from "react"
import Link from "next/link"
import { useParams } from "next/navigation"
import { CheckCircle2, MapPin, PackageSearch, Phone, User } from "lucide-react"
import { Alert } from "@/components/ui/alert"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Skeleton } from "@/components/ui/skeleton"
import { Separator } from "@/components/ui/separator"
import { OrderStatusTracker } from "@/components/orders/order-status-tracker"
import { OrderSummaryCard } from "@/components/orders/order-summary-card"
import { getDemoOrder, PlacedOrder } from "@/lib/orders/demo-order-store"
import { useBusinessConfig } from "@/components/providers/business-config-provider"
import { formatMinutes } from "@/lib/utils/format"

export default function OrderConfirmationPage() {
  const { id } = useParams<{ id: string }>()
  const { currency } = useBusinessConfig()
  const [order, setOrder] = useState<PlacedOrder | null>(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    setOrder(getDemoOrder(id))
    setLoading(false)
  }, [id])

  if (loading) {
    return (
      <div
        className="mx-auto grid w-full max-w-4xl gap-6 px-4 py-12 sm:px-6 lg:px-8"
        aria-hidden="true"
      >
        <div className="flex flex-col items-center gap-2 py-6">
          <Skeleton className="size-14 rounded-full" />
          <Skeleton className="h-7 w-56" />
          <Skeleton className="h-4 w-72" />
        </div>
        <Skeleton className="h-48 w-full" />
        <Skeleton className="h-48 w-full" />
      </div>
    )
  }

  if (!order) {
    return (
      <div className="mx-auto flex w-full max-w-2xl flex-col items-center gap-4 px-4 py-24 text-center sm:px-6 lg:px-8">
        <span className="bg-muted grid size-16 place-items-center rounded-full">
          <PackageSearch className="text-muted-foreground size-7" aria-hidden="true" />
        </span>
        <h1 className="text-2xl font-semibold tracking-tight">Order not found</h1>
        <p className="text-muted-foreground max-w-md text-sm">
          We couldn&apos;t find an order with that reference. It may not exist, or this order was
          placed in a previous session. Your session may have expired.
        </p>
        <Button asChild size="lg" className="mt-2">
          <Link href="/products">Continue shopping</Link>
        </Button>
      </div>
    )
  }

  return (
    <div className="mx-auto w-full max-w-4xl px-4 py-10 sm:px-6 sm:py-14 lg:px-8">
      <div className="flex flex-col items-center gap-3 text-center">
        <span className="bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 grid size-16 place-items-center rounded-full">
          <CheckCircle2 className="size-8" aria-hidden="true" />
        </span>
        <h1 className="text-3xl font-semibold tracking-tight">Order confirmed</h1>
        <p className="text-muted-foreground text-sm">
          Order number:{" "}
          <span className="text-foreground font-semibold tabular-nums">{order.orderNumber}</span>
        </p>
      </div>

      {order.demo ? (
        <Alert variant="warning" className="mt-6" title="Demo order preview">
          <p>No real order was created — this confirmation is generated by the demo order service.</p>
        </Alert>
      ) : null}

      <div className="mt-8 grid items-start gap-6 lg:grid-cols-[1fr_1.2fr]">
        <Card className="gap-4">
          <CardHeader>
            <CardTitle className="text-lg">Delivery status</CardTitle>
          </CardHeader>
          <CardContent>
            <OrderStatusTracker status={order.status} />
          </CardContent>
        </Card>

        <div className="flex flex-col gap-6">
          <Card className="gap-4">
            <CardHeader>
              <CardTitle className="flex items-center gap-2 text-lg">
                <User className="text-primary size-5" aria-hidden="true" />
                Contact &amp; delivery
              </CardTitle>
            </CardHeader>
            <CardContent className="flex flex-col gap-4">
              {order.customer ? (
                <div className="flex flex-col gap-2 text-sm">
                  <p className="flex items-center gap-2">
                    <Phone className="text-muted-foreground size-4 shrink-0" aria-hidden="true" />
                    {order.customer.fullName} · {order.customer.phone}
                  </p>
                  {order.customer.email ? (
                    <p className="text-muted-foreground text-xs">{order.customer.email}</p>
                  ) : null}
                </div>
              ) : null}
              <Separator />
              {order.deliveryAddress ? (
                <div className="flex flex-col gap-2 text-sm">
                  <p className="flex items-center gap-2 font-medium">
                    <MapPin className="text-primary size-4 shrink-0" aria-hidden="true" />
                    {order.deliveryAddress.addressLine}
                  </p>
                  <p className="text-muted-foreground">
                    {order.deliveryAddress.city}, {order.deliveryAddress.area}
                  </p>
                  {order.deliveryAddress.deliveryInstructions ? (
                    <p className="text-muted-foreground text-xs">
                      Instructions: {order.deliveryAddress.deliveryInstructions}
                    </p>
                  ) : null}
                  {order.zoneName ? (
                    <p className="text-muted-foreground flex items-center gap-2 text-xs">
                      <Badge variant="outline">{order.zoneName}</Badge>
                      {order.estimatedMinutes
                        ? `Approx. ${formatMinutes(order.estimatedMinutes)}`
                        : null}
                    </p>
                  ) : null}
                </div>
              ) : null}
            </CardContent>
          </Card>

          <Card className="gap-4">
            <CardHeader>
              <CardTitle className="text-lg">Order summary</CardTitle>
            </CardHeader>
            <CardContent>
              <OrderSummaryCard order={order} currency={currency ?? "USD"} />
            </CardContent>
          </Card>

          <div className="flex flex-col gap-3 sm:flex-row">
            <Button asChild size="lg" className="flex-1">
              <Link href="/products">Order more gas</Link>
            </Button>
            <Button asChild variant="outline" size="lg" className="flex-1">
              <Link href="/account/orders">View my orders</Link>
            </Button>
          </div>
        </div>
      </div>
    </div>
  )
}
